#!/bin/sh

# On first boot, create the ZFS filesystem to store containers.

# PROVIDE: ignition_accounts
# REQUIRE: qemufwcfg, ldconfig
# BEFORE: podman_service
# KEYWORD: firstboot

. /etc/rc.subr

name="create_accounts_from_ignition"
desc="Create accounts from the ignition config"
start_cmd="create_accounts_from_ignition_start"
rcvar="create_accounts_from_ignition_enable"
create_accounts_from_ignition_qemufwcfg_mount_path="/var/run/qemufwcfg"
create_accounts_from_ignition_ignition_path="${create_accounts_from_ignition_qemufwcfg_mount_path}/opt/com.coreos/config"

create_accounts_from_ignition_start()
{
	local count jq username uid keys uidflag home I
	echo "Creating accounts and provisioning SSH keys from ignition"
	jq="/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path}"
	count=$(/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} -r '.passwd.users | length')
	for I in $(seq 0 $(expr ${count} - 1)) ; do
		username=$(/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} -r ".passwd.users[${I}].name")
		if [ -n "${username}" ] ; then
			if id ${username} >/dev/null 2>&1 ; then 
				echo ${username} already exists, not creating.
			else
				uid=$(/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} -r ".passwd.users[${I}].uid")
				uidflag=$(if [ ${uid} = "null" ] ; then echo "" ; else echo "-u ${uid}" ; fi)
				# Create the account.  If any UID is specified, use it.  Disable
				# password auth (these users will just be used via ssh).  Add the
				# user to the wheel group so that they can run podman.
				/usr/sbin/pw useradd ${uidflag} -w no -n ${username} -G wheel -m
				echo "Created user ${username}"
			fi
			home=$(eval echo ~${username})
			echo Installed ssh keys for ${username} to ${home}/.ssh/authorized_keys
			mkdir -p ${home}/.ssh
			/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} -r ".passwd.users[${I}].sshAuthorizedKeys | values[]"
			/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} -r ".passwd.users[${I}].sshAuthorizedKeys | values[]" >> ${home}/.ssh/authorized_keys
			chown ${username} ${home}/.ssh/authorized_keys
			chmod 600 ${home}/.ssh/authorized_keys
			chown ${username} ${home}/.ssh
			chmod 700 ${home}/.ssh
		else
			echo "Invalid user description in Ignition file:"
			/usr/local/bin/jq < ${create_accounts_from_ignition_ignition_path} ".passwd.users[${I}]"
		fi
	done
}

load_rc_config $name
run_rc_command "$1"

