PORTNAME=	qemufwcfg-kmod
DISTVERSION=	0.1
CATEGORIES=	sysutils

LICENSE=	BSD2CLAUSE

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	QEMU firmware config driver
WWW=		https://github.com/davidchisnall/qemufwcfg/tree/main

USE_GITHUB=	yes
GH_ACCOUNT=	davidchisnall
GH_PROJECT=	qemufwcfg
GH_TAGNAME=	d67e278

USES=		kmod fakeroot


.include <bsd.port.mk>
